"""Create GitHub pull requests from validated Phase 3 Terraform patches."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import os
import shutil
import subprocess
import tempfile
import time

from github import Github

from .github_terraform import TerraformSource, parse_github_repo_url
from .local_patch import (
    apply_patch_plan_to_directory,
    run_terraform_fmt,
    run_terraform_validate,
    validate_patch_plan,
)
from .patch_schema import PatchPlan


DEFAULT_PR_TITLE = "Apply Phase 3 FinOps Terraform optimization"
DEFAULT_PR_DESCRIPTION = "Automated Terraform patch generated by PFA Phase 3."
_TRUE_VALUES = {"1", "true", "yes"}


@dataclass
class PullRequestResult:
    created: bool
    branch_name: str | None
    pr_url: str | None
    changed_files: list[str]
    warnings: list[str]
    errors: list[str]


def _run(
    cmd: list[str],
    cwd: Path,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    """Execute one git command while retaining output for error handling."""

    return subprocess.run(
        cmd,
        cwd=cwd,
        text=True,
        capture_output=True,
        check=check,
    )


def _authenticated_repo_url(repo_url: str) -> str:
    """Return an authenticated HTTPS clone URL when a token is configured."""

    token = os.environ.get("GITHUB_TOKEN")
    if not token or not repo_url.startswith("https://github.com/"):
        return repo_url

    owner, repo_name = parse_github_repo_url(repo_url)
    return f"https://x-access-token:{token}@github.com/{owner}/{repo_name}.git"


def _build_branch_name() -> str:
    prefix = os.environ.get("PHASE3_PR_BRANCH_PREFIX", "finops/phase3").strip() or "finops/phase3"
    return f"{prefix}-{int(time.time())}"


def _redact_exception_message(exc: Exception) -> str:
    """Prevent a failed authenticated git command from exposing its token."""

    message = str(exc)
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        message = message.replace(token, "***REDACTED***")
    return message


def create_pull_request_from_patch_plan(
    source: TerraformSource,
    plan: PatchPlan,
    original_files: dict[str, str],
) -> PullRequestResult:
    """Apply a Terraform patch on a branch and open a draft pull request."""

    warnings = list(plan.warnings)

    if not plan.modified_files:
        return PullRequestResult(
            created=False,
            branch_name=None,
            pr_url=None,
            changed_files=[],
            warnings=warnings,
            errors=["No modified files to commit."],
        )

    validation_errors = validate_patch_plan(plan, original_files)
    if validation_errors:
        return PullRequestResult(
            created=False,
            branch_name=None,
            pr_url=None,
            changed_files=[],
            warnings=warnings,
            errors=validation_errors,
        )

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        return PullRequestResult(
            created=False,
            branch_name=None,
            pr_url=None,
            changed_files=[],
            warnings=warnings,
            errors=["GITHUB_TOKEN is required to create a PR."],
        )

    base_branch = os.environ.get("PHASE3_PR_BASE_BRANCH") or source.ref or "main"
    draft = os.environ.get("PHASE3_PR_DRAFT", "1").strip().lower() in _TRUE_VALUES
    branch_name: str | None = None
    temp_dir: Path | None = None

    try:
        temp_dir = Path(tempfile.mkdtemp(prefix="pfa-pr-"))
        repo_dir = temp_dir / "repo"
        _run(
            [
                "git",
                "clone",
                "--branch",
                base_branch,
                _authenticated_repo_url(source.repo_url),
                "repo",
            ],
            temp_dir,
        )

        branch_name = _build_branch_name()
        _run(["git", "checkout", "-b", branch_name], repo_dir)

        changed_files = apply_patch_plan_to_directory(repo_dir, plan, original_files)

        fmt_warning = run_terraform_fmt(repo_dir)
        if fmt_warning:
            warnings.append(fmt_warning)
        validate_warning = run_terraform_validate(repo_dir)
        if validate_warning:
            warnings.append(validate_warning)

        status = _run(["git", "status", "--porcelain"], repo_dir)
        if not status.stdout.strip():
            return PullRequestResult(
                created=False,
                branch_name=branch_name,
                pr_url=None,
                changed_files=[],
                warnings=warnings,
                errors=["No git changes after applying patch."],
            )

        title = plan.pr_title or DEFAULT_PR_TITLE
        description = plan.pr_description or DEFAULT_PR_DESCRIPTION
        _run(["git", "config", "user.email", "pfa-bot@example.com"], repo_dir)
        _run(["git", "config", "user.name", "PFA Phase3 Bot"], repo_dir)
        _run(["git", "add", "."], repo_dir)
        _run(["git", "commit", "-m", title[:72]], repo_dir)
        _run(["git", "push", "origin", branch_name], repo_dir)

        owner, repo_name = parse_github_repo_url(source.repo_url)
        repo = Github(token).get_repo(f"{owner}/{repo_name}")
        pr = repo.create_pull(
            title=title,
            body=description,
            head=branch_name,
            base=base_branch,
            draft=draft,
        )
        return PullRequestResult(
            created=True,
            branch_name=branch_name,
            pr_url=pr.html_url,
            changed_files=changed_files,
            warnings=warnings,
            errors=[],
        )
    except Exception as exc:
        return PullRequestResult(
            created=False,
            branch_name=branch_name,
            pr_url=None,
            changed_files=[],
            warnings=warnings,
            errors=[_redact_exception_message(exc)],
        )
    finally:
        if temp_dir is not None:
            shutil.rmtree(temp_dir, ignore_errors=True)
