"""Normalize Terraform file patches returned by Phase 3 LLM output."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any


DEFAULT_PR_DESCRIPTION = "Automated Terraform patch generated by PFA Phase 3."


def _default_pr_title() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M")
    return f"FinOps Phase 3 Optimization #{ts}"


@dataclass
class ModifiedFile:
    file_path: str
    new_content: str


@dataclass
class PatchPlan:
    modified_files: list[ModifiedFile]
    pr_title: str
    pr_description: str
    warnings: list[str]


def _hcl_scalar(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return f'"{v}"'


def _json_body_to_hcl(body: dict[str, Any], indent: int) -> str:
    prefix = "  " * indent
    lines: list[str] = []
    for k, v in body.items():
        if isinstance(v, dict):
            lines.append(f"{prefix}{k} {{")
            lines.append(_json_body_to_hcl(v, indent + 1))
            lines.append(f"{prefix}}}")
        elif isinstance(v, list):
            for item in v:
                if isinstance(item, dict):
                    lines.append(f"{prefix}{k} {{")
                    lines.append(_json_body_to_hcl(item, indent + 1))
                    lines.append(f"{prefix}}}")
                else:
                    lines.append(f"{prefix}{k} = {_hcl_scalar(item)}")
        else:
            lines.append(f"{prefix}{k} = {_hcl_scalar(v)}")
    return "\n".join(lines)


def _normalize_new_content(content: str) -> str:
    """Convert JSON-encoded Terraform block to HCL if detected; otherwise return as-is."""
    stripped = content.strip()
    if not stripped.startswith("{"):
        return content
    try:
        obj = json.loads(stripped)
    except (json.JSONDecodeError, ValueError):
        return content
    if not isinstance(obj, dict):
        return content

    hcl_blocks: list[str] = []
    for block_type, block_val in obj.items():
        if not isinstance(block_val, dict):
            continue
        if block_type == "resource":
            for res_type, names in block_val.items():
                if not isinstance(names, dict):
                    continue
                for res_name, body in names.items():
                    if not isinstance(body, dict):
                        continue
                    hcl_blocks.append(f'resource "{res_type}" "{res_name}" {{')
                    hcl_blocks.append(_json_body_to_hcl(body, 1))
                    hcl_blocks.append("}")
        elif block_type == "module":
            for mod_name, body in block_val.items():
                if not isinstance(body, dict):
                    continue
                hcl_blocks.append(f'module "{mod_name}" {{')
                hcl_blocks.append(_json_body_to_hcl(body, 1))
                hcl_blocks.append("}")
        else:
            # data, variable, locals, etc. — generic handling
            for name, body in block_val.items():
                if isinstance(body, dict):
                    hcl_blocks.append(f'{block_type} "{name}" {{')
                    hcl_blocks.append(_json_body_to_hcl(body, 1))
                    hcl_blocks.append("}")

    return "\n\n".join(hcl_blocks) if hcl_blocks else content


def _extract_modified_files(obj: dict[str, Any]) -> list[ModifiedFile]:
    """Extract well-formed file content entries without path safety validation."""

    items = obj.get("modified_files") or []
    if not isinstance(items, list):
        return []

    modified_files: list[ModifiedFile] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        file_path = item.get("file_path")
        new_content = item.get("new_content")
        if not isinstance(file_path, str) or not file_path.strip():
            continue
        if not isinstance(new_content, str) or not new_content.strip():
            continue
        modified_files.append(
            ModifiedFile(
                file_path=file_path.strip(),
                new_content=_normalize_new_content(new_content),
            )
        )
    return modified_files


def extract_patch_plan(phase3_output: dict[str, Any]) -> PatchPlan:
    """Extract and merge PR-ready Terraform file contents from LLM run outputs."""

    by_path: dict[str, list[str]] = {}  # file_path → list of HCL blocks to merge
    warnings: list[str] = []
    descriptions: list[str] = []

    runs = phase3_output.get("runs") if isinstance(phase3_output, dict) else None
    if not isinstance(runs, list):
        runs = []

    for run in runs:
        if not isinstance(run, dict):
            continue
        llm = run.get("llm")
        if not isinstance(llm, dict):
            continue
        parsed = llm.get("parsed")
        if not isinstance(parsed, dict):
            continue

        for modified_file in _extract_modified_files(parsed):
            by_path.setdefault(modified_file.file_path, []).append(modified_file.new_content)

        run_title = (parsed.get("pr_title") or "").strip()
        run_description = (parsed.get("pr_description") or "").strip()
        if run_title or run_description:
            pair = f"{run_title}: {run_description}" if run_title and run_description else (run_title or run_description)
            descriptions.append(pair)

        instances = parsed.get("instances")
        if isinstance(instances, dict):
            for resource_id, child in instances.items():
                if not isinstance(child, dict) or "modified_files" not in child:
                    continue
                warnings.append(
                    f"modified_files found inside instances.{resource_id}; prefer top-level modified_files."
                )
                for modified_file in _extract_modified_files(child):
                    by_path.setdefault(modified_file.file_path, []).append(modified_file.new_content)

        findings = parsed.get("findings")
        if isinstance(findings, dict):
            for resource_id, child in findings.items():
                if not isinstance(child, dict) or "modified_files" not in child:
                    continue
                warnings.append(
                    f"modified_files found inside findings.{resource_id}; prefer top-level modified_files."
                )
                for modified_file in _extract_modified_files(child):
                    by_path.setdefault(modified_file.file_path, []).append(modified_file.new_content)
        elif isinstance(findings, list):
            for index, child in enumerate(findings):
                if not isinstance(child, dict) or "modified_files" not in child:
                    continue
                warnings.append(
                    f"modified_files found inside findings[{index}]; prefer top-level modified_files."
                )
                for modified_file in _extract_modified_files(child):
                    by_path.setdefault(modified_file.file_path, []).append(modified_file.new_content)

    merged_files = [
        ModifiedFile(file_path=fp, new_content="\n\n".join(blocks))
        for fp, blocks in by_path.items()
    ]

    return PatchPlan(
        modified_files=merged_files,
        pr_title=_default_pr_title(),
        pr_description="\n\n".join(descriptions) if descriptions else DEFAULT_PR_DESCRIPTION,
        warnings=warnings,
    )
