"""Normalize Terraform file patches returned by Phase 3 LLM output."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


DEFAULT_PR_TITLE = "Apply Phase 3 FinOps Terraform optimization"
DEFAULT_PR_DESCRIPTION = "Automated Terraform patch generated by PFA Phase 3."


@dataclass
class ModifiedFile:
    file_path: str
    new_content: str


@dataclass
class PatchPlan:
    modified_files: list[ModifiedFile]
    pr_title: str
    pr_description: str
    warnings: list[str]


def _extract_modified_files(obj: dict[str, Any]) -> list[ModifiedFile]:
    """Extract well-formed file content entries without path safety validation."""

    items = obj.get("modified_files") or []
    if not isinstance(items, list):
        return []

    modified_files: list[ModifiedFile] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        file_path = item.get("file_path")
        new_content = item.get("new_content")
        if not isinstance(file_path, str) or not file_path.strip():
            continue
        if not isinstance(new_content, str) or not new_content.strip():
            continue
        modified_files.append(
            ModifiedFile(
                file_path=file_path.strip(),
                new_content=new_content,
            )
        )
    return modified_files


def extract_patch_plan(phase3_output: dict[str, Any]) -> PatchPlan:
    """Extract and merge PR-ready Terraform file contents from LLM run outputs."""

    by_path: dict[str, ModifiedFile] = {}
    warnings: list[str] = []
    title: str | None = None
    descriptions: list[str] = []

    runs = phase3_output.get("runs") if isinstance(phase3_output, dict) else None
    if not isinstance(runs, list):
        runs = []

    for run in runs:
        if not isinstance(run, dict):
            continue
        llm = run.get("llm")
        if not isinstance(llm, dict):
            continue
        parsed = llm.get("parsed")
        if not isinstance(parsed, dict):
            continue

        for modified_file in _extract_modified_files(parsed):
            by_path[modified_file.file_path] = modified_file

        run_title = parsed.get("pr_title")
        if title is None and isinstance(run_title, str) and run_title.strip():
            title = run_title.strip()

        run_description = parsed.get("pr_description")
        if isinstance(run_description, str) and run_description.strip():
            descriptions.append(run_description.strip())

        instances = parsed.get("instances")
        if isinstance(instances, dict):
            for resource_id, child in instances.items():
                if not isinstance(child, dict) or "modified_files" not in child:
                    continue
                warnings.append(
                    f"modified_files found inside instances.{resource_id}; prefer top-level modified_files."
                )
                for modified_file in _extract_modified_files(child):
                    by_path[modified_file.file_path] = modified_file

        findings = parsed.get("findings")
        if isinstance(findings, dict):
            for resource_id, child in findings.items():
                if not isinstance(child, dict) or "modified_files" not in child:
                    continue
                warnings.append(
                    f"modified_files found inside findings.{resource_id}; prefer top-level modified_files."
                )
                for modified_file in _extract_modified_files(child):
                    by_path[modified_file.file_path] = modified_file
        elif isinstance(findings, list):
            for index, child in enumerate(findings):
                if not isinstance(child, dict) or "modified_files" not in child:
                    continue
                warnings.append(
                    f"modified_files found inside findings[{index}]; prefer top-level modified_files."
                )
                for modified_file in _extract_modified_files(child):
                    by_path[modified_file.file_path] = modified_file

    return PatchPlan(
        modified_files=list(by_path.values()),
        pr_title=title or DEFAULT_PR_TITLE,
        pr_description="\n\n".join(descriptions) if descriptions else DEFAULT_PR_DESCRIPTION,
        warnings=warnings,
    )
